### ISSUE TITLE
Editorially suppressed clef insertions not reflected properly in variant popups 

### ISSUE THREAD

**Issue by goursaud** [BirminghamConservatoire/JohannesTinctoris#15]
Editorially suppressed clef insertions in sources are not reflected properly in variant popups that *immediately* follow the insertion. The clef configuration is, however, displayed correctly for the variants in rest placement in the third yellow popup.  

`<piece: {mensural: void}, {staf: 5, black}>
<part: 1 >
{clef: C8} Bd {var= (ins.) "{clef: C6}" CS15} {var="mc. sb" Br3 : "Sc" CS15} {var="Pm13" Br3 : "Pm9" CS15} {var= (ins.) "{clef: C8}" CS15}           
</part>
</piece>`

![image](https://user-images.githubusercontent.com/61825706/87959197-6bcbf080-caaa-11ea-8afd-39448e0c34a7.png)

 The problem does not occur if a note is arbitrarily placed between the inserted clef and the opening variant tag.

**Comment by annplaksin** [comment]
It seems like there is a problem in recognising the clef change in the sucsessive variants.
Obviously it works with inserting a positive space...
```
<piece: {mensural: void}, {staf: 5, black}> <part: 1 > {clef: C8} Bd {var= (ins.) "{clef: C6}" CS15} 
[-]{var="mc. sb" Br3 : "Sc" CS15} {var="Pm13" Br3 : "Pm9" CS15} {var= (ins.) "{clef: C8}" CS15} 
</part> </piece>
```
![grafik](https://user-images.githubusercontent.com/12529090/88266190-0ad13200-cccf-11ea-89ba-4dca9a66742d.png)

**Comment by annplaksin** [comment]
Most probably I fixed the problem. I just realized, that the default clefs aren't repeated in variable popups on purpose. So, is this okay for now or would it be better to draw default clefs in variant popups? And follow up question, how urgent would that be?

![grafik](https://user-images.githubusercontent.com/12529090/98244114-32db5d00-1f6f-11eb-952d-81fa5ed2944e.png)
