### ISSUE TITLE
Fermatas over ligatures

### ISSUE THREAD

**Issue by goursaud** [BirminghamConservatoire/JohannesTinctoris#4]
Ligatures can have signa congruentiae over notes but not fermatas (see at the very end):

`<pars>
{clef: C12} {solm: 0} {mens: "C5" edP : "c7" SP edB} SC. <text>Gaude, {var="gloriosa" (ed.) : (transp.) SP},</text> mD <lig>SE SF</lig> mE SG mF <lig>BD LC</lig> <lig>Bc <text>{var=(ins.) "gloriosa" SP}</text> Bd LG</lig> Sa. <text>{var="super omnes speciosa." (ed.) : (transp.) SP}</text> mb Sc SC SE. mF SG Sb <lig>Sa <obl>Sc BG</obl></lig> LC Bc <text>{var="Miserere, mi -" edB edP : "super omnes speciosa" SP}</text> <lig>Bb Bc</lig> BG ba Ba BG bE BE <text>{var="serere" edP 
: "sere" edB : (om.) SP}</text> BD <full>SE. mF SG</full> <lig>BD BG</lig> BD PS9 BG <text>{var="supplicanti" edB edP : (om.) SP}</text> SG mF mE SC. SB. <lig>SC <full>SE</lig> mF</full> {var="LG [-] BC LC" edB : "<lig>LG LC.</lig>" SP : "LG BC LC." edP} <text: -2>{var="Du Faÿ," edB edP : (om.) SP}</text> [-] LF <text>{var="sitque in conspectu" edB edP : (om.) SP}</text> [-] {var="SG [-] SE [-] BF [-] BC <lig><obl>BE BD</obl></lig>" (ed.) : "<lig><obl>SG SE</obl> BF BC <obl>BE BD</obl></lig>" SP} [-] SC. <text>{var="domini" (ed.) : "vale" SP : "tuo" edB : "Dei" edP}</text> mD <lig>SE SF</lig> <lig>SG <obl>SE BD</obl></lig> LC <text>{var=(ins.) "valde decora" SP}</text> 
{var="<lig>SF SG</lig> <lig>Ba LG</lig>" (ed.) : "<lig>SF SG Ba LG</lig>" SP} <text>{var="mors eius" edB edP : (om.) SP} {var="preciosa" (ed.) : (om.) SP : "speciosa" edB edP}.</text> BF PS5 
{var="SC SD." (ed.) : "<lig>SC SD.</lig>" SP} mE {var="<lig>LF LC*</lig>" SP edB : "LF LC" edP} </pars>`
 
It would be helpful if fermatas could avoid dots in ligatures (also at end):
 
`<pars>
{clef: C8} {solm: 0} {mens: "C9" edP : "c9" SP edB} PL9-11x2 PL7-9x2 PL5-7x2 PL7-9x2 PL9-11x2 be <text>Miserere, miserere supplicanti </text> Be Bd Bc Bb Bc Bd BG BF [-] Bb Ba BG PS9 <lig>Bd Be</lig> Sd Bc Lb <text>Du Faÿ,</text> Sc. mb LG {var=(ins.) "." edP} Sa. <text>{var="sitque" edB edP : "sic que" SP} in</text> mb Sc Bd <text>conspectu {var="domini" (ed.) : (om.) SP : "tuo" edB : "Dei" edP}</text> Se Lc <lig>Sb Sc Bd</lig> BG. Sa Sb BG SF BG PS9 <text>{var="mors eius" edB edP : (transp.) SP}</text> Sg Saa Sg <lig>Se Sf</lig> Lg <text>{var="preciosa" (ed.) : "speciosa" edB edP : (transp.) SP}.**See the note in the Discantus concerning the text of this trope.**</text> {var="Bc Bc" SP : "Lc" edB edP} <lig>La. LG*</lig> PL5-7x2 PL7-9x2 PL9-11x2 PL7-9x2 PL9-11 PB9 </pars>`

**Comment by annplaksin** [comment]
I added Fermata to LigatureNote in commit afc45b7f25891a392b0dd2e838bc06e0d1e71bdf but they aren't rendered yet.
Another question: Should fermatas be added to ObliqueNote as well?

**Comment by annplaksin** [comment]
```
<piece: {mensural: void}, {staf: 5, black}>
{clef: C6} {solm: bb ^bbb} {mens: O7} <lig>Lf Lc*</lig> <lig>Lf Lc-*</lig>
</piece>
```

![grafik](https://user-images.githubusercontent.com/12529090/85842303-d043aa80-b79f-11ea-9abe-2cb2dc245473.png)

Okay, it isn't beautiful, but it's there...

**Comment by JohannesTinctoris** [comment]
Yes, please. I'm sure I've encountered this, though I can't put my finger on an instance at the moment.

-jjd

----------------------------------------------------------------
 Dr Jeffrey J. Dean          PI, AHRC Mensural Notation Project
 4 Chandos Road                  Royal Birmingham Conservatoire
 Chorlton-cum-Hardy                     tel: +44(0)161 861 7542
 Manchester  M21 0ST                    fax: +44(0)161 861 7543
 England                    www.earlymusictheory.org/Tinctoris/
 jeffrey.dean@bcu.ac.uk         jeffrey.dean@stingrayoffice.com
================================================================

**Comment by annplaksin** [comment]
Okay, it took some work to figure it out, but I hope it looks bearable:

![grafik](https://user-images.githubusercontent.com/12529090/86259433-4d19be80-bbbc-11ea-85a3-b5ac414b810d.png)
```
<piece: {mensural: void}, {staf: 5, black}>
{clef: C6} {solm: 0} {mens: O7} <lig>Sg <obl>Se*11 Bd*</obl></lig> Se* Se-* <lig>Sg <obl>Se-* Bd-*</obl></lig> [-] Se 
<lig>Sg <obl>Se?11 Bd?</obl></lig> Se? Se-? <lig>Sg <obl>Se-? Bd-?</obl></lig> [-] Se
</piece>
```

**Comment by JohannesTinctoris** [comment]
I like this! It's clear and distinct.

Thanks,
jjd

----------------------------------------------------------------
 Dr Jeffrey J. Dean          PI, AHRC Mensural Notation Project
 4 Chandos Road                  Royal Birmingham Conservatoire
 Chorlton-cum-Hardy                     tel: +44(0)161 861 7542
 Manchester  M21 0ST                    fax: +44(0)161 861 7543
 England                    www.earlymusictheory.org/Tinctoris/
 jeffrey.dean@bcu.ac.uk         jeffrey.dean@stingrayoffice.com
================================================================
