### ISSUE TITLE
Line breaks within label don't work

### ISSUE THREAD

**Issue by annplaksin** [BirminghamConservatoire/JohannesTinctoris#6]
Line breaks within `<label>` don't work either when rotated or not:
```
<treatise>
<example: {full measure}, {mensural: void}, {staf: 5, red}> 
<part: 1> 
	<label: rot90c, 14>
		Test<l/>one
	</label> 
	{clef: F8} {solm: 0} {mens: O9} BF BG LF &F || 
        <label: 14>
		Test<l/>two
	</label> 
</part>
</example>
</treatise>
```

**Comment by annplaksin** [comment]
Can someone please provide a short example where a line break works inside a tag?
It would help a lot to figure out what actually should happen...

Thanks!

**Comment by JohannesTinctoris** [comment]
<piece>
<part: 1>
<pars>
{var="<tacet>Benedictus<l/>tacet.</tacet>" CS49 : "{clef: C8} {solm: bb} {mens: c13} PL5-7x2 <text>Benedictus</text> PL7-9x2 PL9-11x2 PL7-9x2 PL5-7x2 PL7-9x2 PL9-11x2 PL7-9x2 PL5-7x2 PL7-9x2 PL9-11x2 PL7-9x2 PL5-7x2" Car} {var="||" (ed.) : (om.) CS49 : "|" Car}
</pars>
</part>
</piece>

----------------------------------------------------------------
 Dr Jeffrey J. Dean          PI, AHRC Mensural Notation Project
 4 Chandos Road                  Royal Birmingham Conservatoire
 Chorlton-cum-Hardy                     tel: +44(0)161 861 7542
 Manchester  M21 0ST                    fax: +44(0)161 861 7543
 England                    www.earlymusictheory.org/Tinctoris/
 jeffrey.dean@bcu.ac.uk         jeffrey.dean@stingrayoffice.com
================================================================

**Comment by annplaksin** [comment]
Yes, that helps a lot, thank you!

**Comment by annplaksin** [comment]
Better example to play with:
```
<piece: {mensural: void}, {staf: 5, red}> 
<part: 1> 
	<label: rot90c, 14>Test<l/>one</label> 
[-]
	<label: rot90a, 0>Test<l/>again</label> 
[-]
	{clef: F8} {solm: 0} {mens: O9} BF<text>bla</text> BG LF<text>bla<l/>blubb</text> &F || 
        <label: 14>Test<l/>two</label> 
        <tacet>Ta<l/>cet</tacet>
[-][-][-]
        <label: 14>Test{blue}or<l/><red>three</red>**comment**</label> 
[-][-][-]
        <label: rot180, 0>Test<l/><red>four</red>**comment**</label> 
</part>
</piece>
```

**Comment by annplaksin** [comment]
![grafik](https://user-images.githubusercontent.com/12529090/87798355-31fdae80-c84c-11ea-9f42-ac3e4309e2f6.png)
I think I got it done... finally...

Please check if it breaks anything else

**Comment by annplaksin** [comment]
Multiline labels don't work inside variants.

**Comment by annplaksin** [comment]
And now it works:
https://earlymusictheory.github.io/JohannesTinctoris/editor/treatise/ 
```
<treatise>
<example: {full measure}, {mensural: void}, {staf: 5, red}> 
<part: 1> 
	<label: rot90c, 14><red>{var="Contratenor<l/>bassus" V BU Br1 : "Bassus" ModC : "Tenor 2us" Tr88 Luc CS14}</red></label> 
	{clef: F8} {solm: 0} {mens: O9}|| [-][-][-][-]
<label: rot90c, 14><red>Contratenor</red><l/><red>bassus</red></label>
</part>
</example>
</treatise>
```
