### ISSUE TITLE
Fermata causes text to disappear

### ISSUE THREAD

**Issue by goursaud** [BirminghamConservatoire/JohannesTinctoris#9]
The first syllable of 'Amen' is here prevented from displaying by the inclusion of a fermata:

`<piece: {mensural: void}, {staf: 5, black}>
{clef: C6} {solm: 0} {mens: O7} Sd Lc*<text>A -</text>Ld <text>men.</text>
</piece>`

**Comment by JohannesTinctoris** [comment]
Workaround: Put the * after the <text>.

-jjd

----------------------------------------------------------------
 Dr Jeffrey J. Dean          PI, AHRC Mensural Notation Project
 4 Chandos Road                  Royal Birmingham Conservatoire
 Chorlton-cum-Hardy                     tel: +44(0)161 861 7542
 Manchester  M21 0ST                    fax: +44(0)161 861 7543
 England                    www.earlymusictheory.org/Tinctoris/
 jeffrey.dean@bcu.ac.uk         jeffrey.dean@stingrayoffice.com
================================================================

**Comment by annplaksin** [comment]
I am closing this issue now. Please speak up, if there is any reason against it.
